### ISSUE TITLE
Error Running GPT-2

### ISSUE THREAD

**Issue by aboggust** [jeffhj/S-TEST#1]
Hello,

I really enjoyed your paper and thank you for releasing your code!

I am running `run_experiments.py`. Everything runs smoothly except GPT2 throws an error during tokenization.

```
Traceback (most recent call last):
  File "scripts/run_experiments.py", line 191, in <module>
    run_all_LMs(parameters)
  File "scripts/run_experiments.py", line 184, in run_all_LMs
    run_experiments(*parameters, input_param=ip, use_negated_probes=False)
  File "scripts/run_experiments.py", line 141, in run_experiments
    Precision1 = run_evaluation(args, shuffle_data=False, model=model)
  File "/home/aboggust/code/abstraction_alignment/S-TEST/scripts/batch_eval_KB_completion.py", line 530, in main
    ) = model.get_batch_generation(sentences_b, logger=logger)
  File "/nobackup/users/aboggust/bin/miniconda3/envs/nlp/lib/python3.7/site-packages/S_TEST-0.1.2-py3.7.egg/lama/modules/gpt2_connector.py", line 121, in get_batch_generation
  File "/nobackup/users/aboggust/bin/miniconda3/envs/nlp/lib/python3.7/site-packages/S_TEST-0.1.2-py3.7.egg/lama/modules/gpt2_connector.py", line 121, in <listcomp>
  File "/nobackup/users/aboggust/bin/miniconda3/envs/nlp/lib/python3.7/site-packages/S_TEST-0.1.2-py3.7.egg/lama/modules/gpt2_connector.py", line 103, in __get_input_tensors
  File "/nobackup/users/aboggust/bin/miniconda3/envs/nlp/lib/python3.7/site-packages/pytorch_pretrained_bert/tokenization_gpt2.py", line 261, in encode
    return self.convert_tokens_to_ids(self.tokenize(text))
  File "/nobackup/users/aboggust/bin/miniconda3/envs/nlp/lib/python3.7/site-packages/pytorch_pretrained_bert/tokenization_gpt2.py", line 224, in tokenize
    token = ''.join(self.byte_encoder[ord(b)] for b in token)
  File "/nobackup/users/aboggust/bin/miniconda3/envs/nlp/lib/python3.7/site-packages/pytorch_pretrained_bert/tokenization_gpt2.py", line 224, in <genexpr>
    token = ''.join(self.byte_encoder[ord(b)] for b in token)
KeyError: 8217
```

Have you run into this issue before? Or do you know what might be causing it? Thanks!

**Comment by jeffhj** [comment]
Hi Angie,

Thank you for your interest!

I cannot remember exactly whether I have run into this issue before, as it has been more than two years. However, when releasing code to GitHub, I usually clone the repository and run it again on our server to ensure the code works by following the instructions in the README.

From the error message, it seems that the issue is caused by a character whose Unicode code is not in the `byte_encoder`. We can locate the relevant code in the `pytorch_pretrained_bert` package:

```
if sys.version_info[0] == 2:
    token = ''.join(self.byte_encoder[ord(b)] for b in token)
else:
    token = ''.join(self.byte_encoder[b] for b in token.encode('utf-8'))
```

From the code here, I guess it should be expected to call `token = ''.join(self.byte_encoder[b] for b in token.encode('utf-8'))` instead of `token = ''.join(self.byte_encoder[ord(b)] for b in token)`. The reason might be that the package is outdated. You may modify the code here to see if it works.

Additionally, you might want to check if you can run the LAMA repository (https://github.com/facebookresearch/LAMA) normally, as my repository is based on that.

I hope this helps!

**Comment by aboggust** [comment]
Hi Jeff, thank you so much. Your advice was really helpful and resolved my issue!
